name: Deploy to ktn
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: [self-hosted, ktn]
    steps:
      - name: Deploy
        run: |
          cd /opt/services/regicide
          git pull origin main
          npm ci
          npm run build
